/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc_25

import aoc_24.getResourceAsStringCollection

class Day01 {

    fun part1() {
        println("=== Part 1 ===")
        val testInput = getResourceAsStringCollection("2025/day01_test.txt")
        val testResult = getPart1(testInput)
        println("test result - $testResult")
        if (testResult != 3) throw Exception("example 1 not passing")

        val input = getResourceAsStringCollection("2025/day01_input.txt")
        val result = getPart1(input)
        println("result - $result")
    }

    fun part2() {
        println("=== Part 2 ===")
        val testInput = getResourceAsStringCollection("2025/day01_test.txt")
        val testResult = getPart2(testInput)
        println("test result - $testResult")
        if (testResult != 6) throw Exception("example 2 not passing")

        val input = getResourceAsStringCollection("2025/day01_input.txt")
        val result = getPart2(input)
        println("result - $result")
    }

    private fun getPart1(input: List<String>): Int {
        var result = 0
        var pointsTo = 50
        input.forEach { line ->
            val dir = line.first()
            val distance = line.drop(1).toInt()
            val x = if (dir == 'R') 1 else -1

            pointsTo += x * distance
            while (pointsTo < 0) { pointsTo += 100 }
            while (pointsTo > 99) { pointsTo -= 100 }

            if (pointsTo == 0) result++
        }
        return result
    }

    private fun getPart2(input: List<String>): Int {
        var result = 0
        var pointsTo = 50
        input.forEach { line ->
            val dir = line.first()
            val distance = line.drop(1).toInt()
            val x = if (dir == 'R') 1 else -1


            pointsTo += x * distance

            if (pointsTo == 100) pointsTo = 0

            while (pointsTo < 0) {
                println("$pointsTo:increment:+")
                pointsTo += 100
                result++
            }
            while (pointsTo > 99) {
                println("$pointsTo:increment:-")
                pointsTo -= 100
                result++
            }

            if (pointsTo == 0) {
                println("$pointsTo:increment:0")
                result++
            }

            println("$pointsTo - $result")
        }
        return result
    }
}

fun main() {
    Day01().apply {
        part1()
        //TODO not counting properly
        //part2()
    }
}
