/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc_25

import aoc_24.getResourceAsStringCollection

class Day04 {

    fun part1() {
        println("=== Part 1 ===")
        val testInput = getResourceAsStringCollection("2025/day04_test.txt")
        val testResult = getPart1(testInput)
        println("test result - $testResult")
        if (testResult != 13L) throw Exception("example 1 not passing")

        val input = getResourceAsStringCollection("2025/day04_input.txt")
        val result = getPart1(input)
        println("result - $result")
    }

    fun part2() {
        println("=== Part 2 ===")
        val testInput = getResourceAsStringCollection("2025/day04_test.txt")
        val testResult = getPart2(testInput)
        println("test result - $testResult")
        if (testResult != 43L) throw Exception("example 2 not passing")

        val input = getResourceAsStringCollection("2025/day04_input.txt")
        val result = getPart2(input)
        println("result - $result")
    }

    private fun getPart1(input: List<String>): Long {
        var result = 0L

        // process locations
        val rolls = mutableSetOf<Pair<Long, Long>>()
        input.forEachIndexed { row, line ->
            line.forEachIndexed { col, c ->
                if (c == '@') rolls.add(row.toLong() to col.toLong())
            }
        }

        rolls.forEach { roll -> if (rolls.canBeRemoved(roll)) result++ }

        return result
    }

    private fun Set<Pair<Long, Long>>.canBeRemoved(roll: Pair<Long, Long>): Boolean {
        val rolls = this
        val (row, col) = roll

        var score = 0
        if (rolls.contains(row - 1 to col - 1)) score++
        if (rolls.contains(row - 1 to col)) score++
        if (rolls.contains(row - 1 to col + 1)) score++
        if (rolls.contains(row to col - 1)) score++
        if (rolls.contains(row to col + 1)) score++
        if (rolls.contains(row + 1 to col - 1)) score++
        if (rolls.contains(row + 1 to col)) score++
        if (rolls.contains(row + 1 to col + 1)) score++

        return score < 4
    }

    private fun getPart2(input: List<String>): Long {
        // process locations
        val rolls = mutableSetOf<Pair<Long, Long>>()
        input.forEachIndexed { row, line ->
            line.forEachIndexed { col, c ->
                if (c == '@') rolls.add(row.toLong() to col.toLong())
            }
        }

        var result = 0L
        var eligibleForRemoval = rolls.filter { rolls.canBeRemoved(it) }
        while (eligibleForRemoval.isNotEmpty()) {
            result += eligibleForRemoval.count()
            rolls.removeAll(eligibleForRemoval.toSet())
            eligibleForRemoval = rolls.filter { rolls.canBeRemoved(it) }
        }

        return result
    }
}

fun main() {
    Day04().apply {
        part1()
        part2()
    }
}
