/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc_25

import aoc_24.getResourceAsStringCollection

class Day07 {

    fun part1() {
        println("=== Part 1 ===")
        val testInput = getResourceAsStringCollection("2025/day07_test.txt")
        val testResult = getPart1(testInput)
        println("test result - $testResult")
        if (testResult != 21L) throw Exception("example 1 not passing")

        val input = getResourceAsStringCollection("2025/day07_input.txt")
        val result = getPart1(input)
        println("result - $result")
    }

    fun part2() {
        println("=== Part 2 ===")
        val testInput = getResourceAsStringCollection("2025/day07_test.txt")
        val testResult = getPart2(testInput)
        println("test result - $testResult")
        if (testResult != 40L) throw Exception("example 2 not passing")

        val input = getResourceAsStringCollection("2025/day07_input.txt")
        val result = getPart2(input)
        println("result - $result")
    }

    private fun getPart1(input: List<String>): Long {
        var result = 0L

        val beams = mutableSetOf(input.first().indexOf("S"))
        input.drop(1).forEach { line ->
            val splitters = line.mapIndexedNotNull { index, ch -> if (ch == '^') index else null }
            splitters.forEach { splitter ->
                if (beams.contains(splitter)) {
                    result++
                    beams.remove(splitter)
                    if (splitter > 0) beams.add(splitter - 1)
                    if (splitter < line.length - 1) beams.add(splitter + 1)
                } else {
                    // no-op
                }
            }
        }

        return result
    }

    private fun getPart2(input: List<String>): Long {
        val beams = mutableMapOf<Int, Long>()
        beams[input.first().indexOf("S")] = 1L
        input.drop(1).forEach { line ->
            val splitters = line.mapIndexedNotNull { index, ch -> if (ch == '^') index else null }
            splitters.forEach { splitter ->
                if (beams.contains(splitter)) {
                    val originalBeamWeight = beams.getOrElse(splitter) { 0 }
                    beams.remove(splitter)
                    if (splitter > 0) {
                        val newBeam = splitter - 1
                        beams[newBeam] = beams.getOrElse(newBeam) { 0 } + originalBeamWeight
                    }
                    if (splitter < line.length - 1) {
                        val newBeam = splitter + 1
                        beams[newBeam] = beams.getOrElse(newBeam) { 0 } + originalBeamWeight
                    }
                } else {
                    // no-op
                }
            }
        }
        return beams.values.sum()
    }
}

fun main() {
    Day07().apply {
        part1()
        part2()
    }
}
