/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc_25

import aoc_24.getResourceAsStringCollection
import kotlin.math.max

class Day03 {

    fun part1() {
        println("=== Part 1 ===")
        val testInput = getResourceAsStringCollection("2025/day03_test.txt")
        val testResult = getPart1(testInput)
        println("test result - $testResult")
        if (testResult != 357L) throw Exception("example 1 not passing")

        val input = getResourceAsStringCollection("2025/day03_input.txt")
        val result = getPart1(input)
        println("result - $result")
    }

    fun part2() {
        println("=== Part 2 ===")
        val testInput = getResourceAsStringCollection("2025/day03_test.txt")
        val testResult = getPart2(testInput)
        println("test result - $testResult")
        if (testResult != 3121910778619L) throw Exception("example 2 not passing")

        val input = getResourceAsStringCollection("2025/day03_input.txt")
        val result = getPart2(input)
        println("result - $result")
    }

    private fun getPart1(input: List<String>): Long {
        var result = 0L
        input.forEach { bank ->
            val batteries = bank.map { it.digitToInt() }
            var maxJoltage = 0
            (0..<batteries.size).forEach { i ->
                (i+1..<batteries.size).forEach { j ->
                    val joltage = batteries[i] * 10 + batteries[j]
                    maxJoltage = max(maxJoltage, joltage)
                }
            }
            result += maxJoltage
        }
        return result
    }

    private fun getPart2(input: List<String>): Long {
        var result = 0L
        input.forEach { bank ->
            val batteries = bank.map { it.digitToInt() }
            result += batteries.getMaxJoltage()
        }
        return result
    }

    private val maxJoltageDigits = 12

    private fun List<Int>.getMaxJoltage(): Long {
        val rawJoltage = mutableListOf<Int>()
        var nextStart = 0
        (0..<maxJoltageDigits).forEach { i ->
            val numbersLeft = maxJoltageDigits - i

            val subListStart = nextStart
            val subListEnd = size - numbersLeft + 1

            val subList = this.subList(subListStart, subListEnd)
            val subListMax = subList.max()
            nextStart += subList.indexOf(subListMax) + 1
            rawJoltage.add(subListMax)
        }
        return rawJoltage.joinToString("").toLong()
    }
}

fun main() {
    Day03().apply {
        part1()
        part2()
    }
}
