/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc_25

import aoc_24.getResourceAsStringCollection

class Day02 {

    fun part1() {
        println("=== Part 1 ===")
        val testInput = getResourceAsStringCollection("2025/day02_test.txt")
        val testResult = getPart1(testInput)
        println("test result - $testResult")
        if (testResult != 1227775554L) throw Exception("example 1 not passing")

        val input = getResourceAsStringCollection("2025/day02_input.txt")
        val result = getPart1(input)
        println("result - $result")
    }

    fun part2() {
        println("=== Part 2 ===")
        val testInput = getResourceAsStringCollection("2025/day02_test.txt")
        val testResult = getPart2(testInput)
        println("test result - $testResult")
        if (testResult != 4174379265L) throw Exception("example 2 not passing")

        val input = getResourceAsStringCollection("2025/day02_input.txt")
        val result = getPart2(input)
        println("result - $result")
    }

    private fun getPart1(input: List<String>): Long {
        var result = 0L
        input.forEach { line ->
            line.split(",").forEach { range ->
                val (start, end) = range.split("-").let { it[0].toLong() to it[1].toLong() }
                (start..end).forEach { number ->
                    if (number.isInvalid()) result += number
                }
            }
        }
        return result
    }

    private fun Long.isInvalid(): Boolean {
        val value = toString()
        if (value.length % 2 != 0) return false
        val half = value.length / 2
        return value.take(half) == value.takeLast(half)
    }

    private fun getPart2(input: List<String>): Long {
        var result = 0L
        input.forEach { line ->
            line.split(",").forEach { range ->
                val (start, end) = range.split("-").let { it[0].toLong() to it[1].toLong() }
                (start..end).forEach { number ->
                    if (number.isInvalid2()) {
                        result += number
                    }
                }
            }
        }
        return result
    }

    private fun Long.isInvalid2(): Boolean {
        val value = toString()
        val half = value.length / 2

        (1..half).forEach { window ->
            if (value.length % window == 0) {
                val windows = value.windowed(window, window)
                if (windows.size > 1) {
                    if (windows.toSet().size == 1) return true
                }
            }
        }
        return false
    }
}

fun main() {
    Day02().apply {
        part1()
        part2()
    }
}
